### ISSUE TITLE
视频录制背景图是否需要更新

### ISSUE THREAD

**Issue by 180909** [PyConChina/PyConChina2021#4]
[recording1.png](https://github.com/PyConChina/PyConChina2021/blob/main/public/assets/images/recording1.png)
[recording2.png](https://github.com/PyConChina/PyConChina2021/blob/main/public/assets/images/recording2.png)
[recording_bg.png](https://github.com/PyConChina/PyConChina2021/blob/main/public/assets/images/recording_bg.png)
这些图片中的logo和日期都是2020年的，请问是否需要更新一下？

**Comment by frostming** [comment]
前两张图仅为录制示范用，没什么关系，第三张可以考虑换掉
