### ISSUE TITLE
cn.pycon.org points to 2020 website

### ISSUE THREAD

**Issue by greyli** [PyConChina/PyConChina2021#7]
此前打开 https://cn.pycon.org 指向新网站，现在打开指向 2020 年的网站。另外 https://pyconchina2021.vercel.app 返回 404 页面。

**Comment by frostming** [comment]
1. DNS 缓存，强制刷新试试（Ctrl + Shift + R）
2. 这个是内部地址，不应该直接访问，其实页面是在/2021端点下，我改下项目url

**Comment by frostming** [comment]
机器上访问过2020网站的都可能有第一个问题，我尝试的清dns缓存的方法也不奏效，有没有成功的方法？

**Comment by greyli** [comment]
两台电脑，均使用 Chrome 访问过 2020 网站。Windows 下正常，macOS 下有下面这些行为：

- 隐私模式（Incognito）下访问根地址会跳转到 /2021
- 非隐私模式直接访问根地址不会跳转
- 非隐私模式在根地址页面按下 Ctrl + Shift + R 后跳转 /2021，之后重新访问根地址仍然不跳转
- 清理 DNS 缓存后无效
